# -*- coding: utf-8 -*-
{
    'name': 'eCommerce Base Modules',
    'version': '1.0',
    'summary': 'Provides all Website Ecommerce modules for a basic installation.',
    'description': '',
    'category': 'eCommerce',
    'author': 'Comunitea',
    'website': 'http://www.comunitea.com',
    'license': 'AGPL-3',
    'contributors': [
        'Pavel Smirnov <pavel@comunitea.com>',
        'Rubén Seijas <ruben@comunitea.com>',
    ],
    'depends': [
        'l10n_es',
        'base_search_fuzzy',
        'website',
        'website_mail',
        'website_logo',
        'website_sale',
        'website_sale_require_login',
        'website_sale_require_legal',
        'website_sale_management',
        'website_sale_stock',
        'website_sale_comparison',
        'website_sale_wishlist',
        'website_sale_delivery',
        'website_cookie_notice',
        'website_crm_recaptcha',
        'website_crm_privacy_policy',
        'website_crm_phone_validation',
        'website_payment',
        'website_menu_by_user_status',
        'website_odoo_debranding',
    ],
    'data': [
        'templates/head.xml',
        'templates/assets.xml',
    ],
    'images': [
        '/static/description/icon.png',
    ],
    'qweb': [
    ],
    'installable': True,
    'application': False,
}
